CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  auth0_user_id VARCHAR(255),
  user_role VARCHAR(50),
  is_approved BOOLEAN DEFAULT FALSE,
  user_created_time TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  approved_time TIMESTAMP WITHOUT TIME ZONE
);
